### ISSUE TITLE
[Security] ENV Credentials Visible

### ISSUE THREAD

**Issue by YashKumarVerma** [CodeChefVIT/ffds#4]
Issue
---
However the `.env` File was removed, the contents can still be viewed through the commit history.

Solution
---
Overwrite the commit history and force rewrite the master branch.

Reference
---
[Commit Details](https://github.com/CodeChefVIT/ffds/commit/29d4720e9cc5b9bc44bd10fac1c32bb0944b4190)

**Comment by L04DB4L4NC3R** [comment]
Thank you for noticing. They have been invalidated
