### ISSUE TITLE
Delete old code.

### ISSUE THREAD

**Issue by akshatvg** [CodeChefVIT/FFDS#44]
@Ishan-001 delete Rekha's old app code.

@avishj delete your old Bulma code.

**Comment by avishj** [comment]
Fixed in #47

**Comment by akshatvg** [comment]
@avishj there's still a folder called old on the organisation's repo. If it's not on your repo, then rebase -> delete -> send PR.

**Comment by avishj** [comment]
Yeah, I made a mistake, fixed it in #48 .

**Comment by DiptoChakrabarty** [comment]
> Yeah, I made a mistake, fixed it in #48 .

The old folder is still present issue has not been fixed

**Comment by avishj** [comment]
Finally fixed in #49
