### ISSUE TITLE
Delete node_modules and .env from pushed repo.

### ISSUE THREAD

**Issue by akshatvg** [CodeChefVIT/FFDS#5]
@avishj @vijeta04

**Comment by avishj** [comment]
I don't have that folder in my repo. Let me try to pull from this to my fork, then add it to gitignore and submit a PR

**Comment by avishj** [comment]
Added PR #7

**Comment by akshatvg** [comment]
@avishj 
.env has still not been deleted from master.

@vijeta04 
Both the files haven't been deleted from Backend.
